//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PardakhtVasetServices
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EPayRequestModel", Namespace="http://schemas.datacontract.org/2004/07/PardakhtVaset.Services.DataContract")]
    [System.SerializableAttribute()]
    public partial class EPayRequestModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BearerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallBackUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort ExpiresAfterDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InvoiceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAutoRedirectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bearer {
            get {
                return this.BearerField;
            }
            set {
                if ((object.ReferenceEquals(this.BearerField, value) != true)) {
                    this.BearerField = value;
                    this.RaisePropertyChanged("Bearer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallBackUrl {
            get {
                return this.CallBackUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.CallBackUrlField, value) != true)) {
                    this.CallBackUrlField = value;
                    this.RaisePropertyChanged("CallBackUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort ExpiresAfterDays {
            get {
                return this.ExpiresAfterDaysField;
            }
            set {
                if ((this.ExpiresAfterDaysField.Equals(value) != true)) {
                    this.ExpiresAfterDaysField = value;
                    this.RaisePropertyChanged("ExpiresAfterDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InvoiceDate {
            get {
                return this.InvoiceDateField;
            }
            set {
                if ((this.InvoiceDateField.Equals(value) != true)) {
                    this.InvoiceDateField = value;
                    this.RaisePropertyChanged("InvoiceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceNumberField, value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAutoRedirect {
            get {
                return this.IsAutoRedirectField;
            }
            set {
                if ((this.IsAutoRedirectField.Equals(value) != true)) {
                    this.IsAutoRedirectField = value;
                    this.RaisePropertyChanged("IsAutoRedirect");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationResult", Namespace="http://schemas.datacontract.org/2004/07/PardakhtVaset.Services.DataContract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PardakhtVasetServices.EPayRequestCheckResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PardakhtVasetServices.CapitalUnblockResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PardakhtVasetServices.CapitalCancelResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(PardakhtVasetServices.EPayRequestResult))]
    public partial class OperationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<PardakhtVasetServices.ExceptionType> ExceptionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<PardakhtVasetServices.ExceptionType> ExceptionType {
            get {
                return this.ExceptionTypeField;
            }
            set {
                if ((this.ExceptionTypeField.Equals(value) != true)) {
                    this.ExceptionTypeField = value;
                    this.RaisePropertyChanged("ExceptionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EPayRequestCheckResult", Namespace="http://schemas.datacontract.org/2004/07/PardakhtVaset.Services.DataContract")]
    [System.SerializableAttribute()]
    public partial class EPayRequestCheckResult : PardakhtVasetServices.OperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankReferenceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PardakhtVasetServices.RequestStatus RequestStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> VerifyDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankReferenceId {
            get {
                return this.BankReferenceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.BankReferenceIdField, value) != true)) {
                    this.BankReferenceIdField = value;
                    this.RaisePropertyChanged("BankReferenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PardakhtVasetServices.RequestStatus RequestStatus {
            get {
                return this.RequestStatusField;
            }
            set {
                if ((this.RequestStatusField.Equals(value) != true)) {
                    this.RequestStatusField = value;
                    this.RaisePropertyChanged("RequestStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> VerifyDate {
            get {
                return this.VerifyDateField;
            }
            set {
                if ((this.VerifyDateField.Equals(value) != true)) {
                    this.VerifyDateField = value;
                    this.RaisePropertyChanged("VerifyDate");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CapitalUnblockResult", Namespace="http://schemas.datacontract.org/2004/07/PardakhtVaset.Services.DataContract")]
    [System.SerializableAttribute()]
    public partial class CapitalUnblockResult : PardakhtVasetServices.OperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UnblockedAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnblockedAmount {
            get {
                return this.UnblockedAmountField;
            }
            set {
                if ((this.UnblockedAmountField.Equals(value) != true)) {
                    this.UnblockedAmountField = value;
                    this.RaisePropertyChanged("UnblockedAmount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CapitalCancelResult", Namespace="http://schemas.datacontract.org/2004/07/PardakhtVaset.Services.DataContract")]
    [System.SerializableAttribute()]
    public partial class CapitalCancelResult : PardakhtVasetServices.OperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CancelledAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CancelledAmount {
            get {
                return this.CancelledAmountField;
            }
            set {
                if ((this.CancelledAmountField.Equals(value) != true)) {
                    this.CancelledAmountField = value;
                    this.RaisePropertyChanged("CancelledAmount");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EPayRequestResult", Namespace="http://schemas.datacontract.org/2004/07/PardakhtVaset.Services.DataContract")]
    [System.SerializableAttribute()]
    public partial class EPayRequestResult : PardakhtVasetServices.OperationResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestTokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentUrl {
            get {
                return this.PaymentUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentUrlField, value) != true)) {
                    this.PaymentUrlField = value;
                    this.RaisePropertyChanged("PaymentUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestToken {
            get {
                return this.RequestTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestTokenField, value) != true)) {
                    this.RequestTokenField = value;
                    this.RaisePropertyChanged("RequestToken");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionType", Namespace="http://schemas.datacontract.org/2004/07/PardakhtVaset.Services.DataContract")]
    public enum ExceptionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exception = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArgumentNullException = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArgumentException = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidOperationException = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ArgumentOutOfRangeException = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SecurityException = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestStatus", Namespace="http://schemas.datacontract.org/2004/07/Septa.PardakhtVaset.Domain.Models")]
    public enum RequestStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Initiated = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Expired = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Viewed = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DividedEPayRequestModel", Namespace="http://schemas.datacontract.org/2004/07/PardakhtVaset.Services.DataContract")]
    [System.SerializableAttribute()]
    public partial class DividedEPayRequestModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallBackUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PardakhtVasetServices.DividedEPayRequestDivisionModel[] DivisionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ushort ExpiresAfterDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InvoiceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAutoRedirectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBlockingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallBackUrl {
            get {
                return this.CallBackUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.CallBackUrlField, value) != true)) {
                    this.CallBackUrlField = value;
                    this.RaisePropertyChanged("CallBackUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PardakhtVasetServices.DividedEPayRequestDivisionModel[] Divisions {
            get {
                return this.DivisionsField;
            }
            set {
                if ((object.ReferenceEquals(this.DivisionsField, value) != true)) {
                    this.DivisionsField = value;
                    this.RaisePropertyChanged("Divisions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ushort ExpiresAfterDays {
            get {
                return this.ExpiresAfterDaysField;
            }
            set {
                if ((this.ExpiresAfterDaysField.Equals(value) != true)) {
                    this.ExpiresAfterDaysField = value;
                    this.RaisePropertyChanged("ExpiresAfterDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InvoiceDate {
            get {
                return this.InvoiceDateField;
            }
            set {
                if ((this.InvoiceDateField.Equals(value) != true)) {
                    this.InvoiceDateField = value;
                    this.RaisePropertyChanged("InvoiceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber {
            get {
                return this.InvoiceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceNumberField, value) != true)) {
                    this.InvoiceNumberField = value;
                    this.RaisePropertyChanged("InvoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAutoRedirect {
            get {
                return this.IsAutoRedirectField;
            }
            set {
                if ((this.IsAutoRedirectField.Equals(value) != true)) {
                    this.IsAutoRedirectField = value;
                    this.RaisePropertyChanged("IsAutoRedirect");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBlocking {
            get {
                return this.IsBlockingField;
            }
            set {
                if ((this.IsBlockingField.Equals(value) != true)) {
                    this.IsBlockingField = value;
                    this.RaisePropertyChanged("IsBlocking");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DividedEPayRequestDivisionModel", Namespace="http://schemas.datacontract.org/2004/07/PardakhtVaset.Services.DataContract")]
    [System.SerializableAttribute()]
    public partial class DividedEPayRequestDivisionModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApiKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApiKey {
            get {
                return this.ApiKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ApiKeyField, value) != true)) {
                    this.ApiKeyField = value;
                    this.RaisePropertyChanged("ApiKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PardakhtVasetServices.IPayRequest")]
    public interface IPayRequest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayRequest/Create", ReplyAction="http://tempuri.org/IPayRequest/CreateResponse")]
        PardakhtVasetServices.EPayRequestResult Create(string apiKey, PardakhtVasetServices.EPayRequestModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayRequest/Check", ReplyAction="http://tempuri.org/IPayRequest/CheckResponse")]
        PardakhtVasetServices.EPayRequestCheckResult Check(string apiKey, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayRequest/Verify", ReplyAction="http://tempuri.org/IPayRequest/VerifyResponse")]
        bool Verify(string apiKey);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayRequest/CreateDividedEPayRequest", ReplyAction="http://tempuri.org/IPayRequest/CreateDividedEPayRequestResponse")]
        PardakhtVasetServices.EPayRequestResult CreateDividedEPayRequest(string apiKey, PardakhtVasetServices.DividedEPayRequestModel request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayRequest/UnblockAmount", ReplyAction="http://tempuri.org/IPayRequest/UnblockAmountResponse")]
        PardakhtVasetServices.CapitalUnblockResult UnblockAmount(string apiKey, decimal amount, string shareApiKey, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPayRequest/CancelAmount", ReplyAction="http://tempuri.org/IPayRequest/CancelAmountResponse")]
        PardakhtVasetServices.CapitalCancelResult CancelAmount(string apiKey, decimal amount, string shareApiKey, string shebaNO, string description);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPayRequestChannel : PardakhtVasetServices.IPayRequest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PayRequestClient : System.ServiceModel.ClientBase<PardakhtVasetServices.IPayRequest>, PardakhtVasetServices.IPayRequest {
        
        public PayRequestClient() {
        }
        
        public PayRequestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PayRequestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PayRequestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PayRequestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PardakhtVasetServices.EPayRequestResult Create(string apiKey, PardakhtVasetServices.EPayRequestModel request) {
            return base.Channel.Create(apiKey, request);
        }
        
        public PardakhtVasetServices.EPayRequestCheckResult Check(string apiKey, string token) {
            return base.Channel.Check(apiKey, token);
        }
        
        public bool Verify(string apiKey) {
            return base.Channel.Verify(apiKey);
        }
        
        public PardakhtVasetServices.EPayRequestResult CreateDividedEPayRequest(string apiKey, PardakhtVasetServices.DividedEPayRequestModel request) {
            return base.Channel.CreateDividedEPayRequest(apiKey, request);
        }
        
        public PardakhtVasetServices.CapitalUnblockResult UnblockAmount(string apiKey, decimal amount, string shareApiKey, string description) {
            return base.Channel.UnblockAmount(apiKey, amount, shareApiKey, description);
        }
        
        public PardakhtVasetServices.CapitalCancelResult CancelAmount(string apiKey, decimal amount, string shareApiKey, string shebaNO, string description) {
            return base.Channel.CancelAmount(apiKey, amount, shareApiKey, shebaNO, description);
        }
    }
}
